# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf1a83a2106cf32cc2e9192daa1458c8d81522b658132ab129aa74184f1acba56e13b70cc06c9c7003128febd3ac04e7b31c11c06cfb5838270251bbf0cdff5c

test:
  secret_key_base: b3cb62d96cdc25fd2516afd4469819883ec51a8909a767ea1462b4c610bc6116f771de4769fc2fed5cb956511e4d77cfcacb1c38ab276cad8a71655da23b39a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
